# Testing http requests with Visual Studio Code REST Client extension

## Items (test resource/endpoints using hard-coded mock data)

### get all items
GET http://localhost:3000/api/items

### get item by id
GET http://localhost:3000/api/items/3

### post a new item
POST http://localhost:3000/api/items
content-type: application/json

{
  "name": "Sitruuna"
}

### modify an existing item (by using item's id as a parameter in url)
PUT http://localhost:3000/api/items/3
content-type: application/json

{
  "name": "new name for this item"
}

### delete an item (by id)
DELETE http://localhost:3000/api/items/3


###########################
## Users resource endpoints

### get all users
GET http://localhost:3000/api/users

### get user by id
GET http://localhost:3000/api/users/3

### create a new user (user registration)
POST http://localhost:3000/api/users
content-type: application/json

{
  "username": "melooni5",
  "password": "melooni4x",
  "email" : "melooni4@mahtava.fi"
  
}

### modify an existing user by id
PUT http://localhost:3000/api/users/3
content-type: application/json

{
  "username": "editedname",
  "password": "editedpasswordx",
  "email": "editedmail@example.com"
}

### delete a user (by id)
DELETE http://localhost:3000/api/users/3

### user login
POST http://localhost:3000/api/users/login
content-type: application/json

{
  "username": "melooni2",
  "password": "meloonix"
}
###

GET http://localhost:3000/api/entries

###
GET http://localhost:3000/api/entries/2

###
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "username": "melooni2",
  "password": "meloonix"
}

### get my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6Im5ld3VzZXJuYW1lIiwicGFzc3dvcmQiOiIkMmIkMTAkcklIUnZFbE4wWENBZGU2VzRRbzh4Lm16SW1Td0pVR0JuL1phWVJuQzd5dFZqaHVPUy9wUFciLCJlbWFpbCI6Im5ld2VtYWlsQGV4YW1wbGUuY29tIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDItMjFUMTk6MTA6MjMuMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQwMTY1ODY1LCJleHAiOjE3NDAyNTIyNjV9.AweujjID0xXXnECYIhCU_WwzH60gvbBQiYCUjdMFjxg
### post a new entry
POST http://localhost:3000/api/entries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNywidXNlcm5hbWUiOiJtZWxvb25pMiIsInBhc3N3b3JkIjoiJDJiJDEwJDRPa2lMWEJQejIudU5BVmlZQ2xvck9qdW1VNUlWR0gva1NseGRtUGJGMm9WaThEZkRHakRhIiwiZW1haWwiOiJtZWxvb25pQG1haHRhdmEuZmkiLCJjcmVhdGVkX2F0IjoiMjAyNS0wMi0yNlQxMjoxOTowOC4wMDBaIiwidXNlcl9sZXZlbCI6InJlZ3VsYXIiLCJpYXQiOjE3NDA1NzIzNTUsImV4cCI6MTc0MDY1ODc1NX0.jtTTX2iQ5wboiUvWuH8PcVsUgHS5LkwPemdfHpBpZAc
content-type: application/json

{
 "entry_date": "",
 "mood": 2,
 "weight": "str",
 "sleep_hours": 30,
 "notes": "tosi kiva fiilis"
}




### Get user's entries
GET http://localhost:3000/api/entries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6Im5ld3VzZXJuYW1lIiwicGFzc3dvcmQiOiIkMmIkMTAkcklIUnZFbE4wWENBZGU2VzRRbzh4Lm16SW1Td0pVR0JuL1phWVJuQzd5dFZqaHVPUy9wUFciLCJlbWFpbCI6Im5ld2VtYWlsQGV4YW1wbGUuY29tIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDItMjFUMTk6MTA6MjMuMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQwMTY1ODY1LCJleHAiOjE3NDAyNTIyNjV9.AweujjID0xXXnECYIhCU_WwzH60gvbBQiYCUjdMFjxg
###
PUT http://localhost:3000/api/entries/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6Im5ld3VzZXJuYW1lIiwicGFzc3dvcmQiOiIkMmIkMTAkcklIUnZFbE4wWENBZGU2VzRRbzh4Lm16SW1Td0pVR0JuL1phWVJuQzd5dFZqaHVPUy9wUFciLCJlbWFpbCI6Im5ld2VtYWlsQGV4YW1wbGUuY29tIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDItMjFUMTk6MTA6MjMuMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQwMTY1ODY1LCJleHAiOjE3NDAyNTIyNjV9.AweujjID0xXXnECYIhCU_WwzH60gvbBQiYCUjdMFjxg
Content-Type: application/json

{
 "entry_date": "2025-02-21",
 "mood": "surullinen",
 "weight": 40,
 "sleep_hours": 2,
 "notes": "Javascript hajottaa"
}

###
PUT http://localhost:3000/api/users/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6Im5ld3VzZXJuYW1lIiwicGFzc3dvcmQiOiIkMmIkMTAkcklIUnZFbE4wWENBZGU2VzRRbzh4Lm16SW1Td0pVR0JuL1phWVJuQzd5dFZqaHVPUy9wUFciLCJlbWFpbCI6Im5ld2VtYWlsQGV4YW1wbGUuY29tIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDItMjFUMTk6MTA6MjMuMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQwMTY1ODY1LCJleHAiOjE3NDAyNTIyNjV9.AweujjID0xXXnECYIhCU_WwzH60gvbBQiYCUjdMFjxg
content-type: application/json

{
  "username": "editedname",
  "password": "editedpasswordx",
  "email": "editedmail@example.com"
}
###
DELETE http://localhost:3000/api/entries/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6Im5ld3VzZXJuYW1lIiwicGFzc3dvcmQiOiIkMmIkMTAkcklIUnZFbE4wWENBZGU2VzRRbzh4Lm16SW1Td0pVR0JuL1phWVJuQzd5dFZqaHVPUy9wUFciLCJlbWFpbCI6Im5ld2VtYWlsQGV4YW1wbGUuY29tIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDItMjFUMTk6MTA6MjMuMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQwMTY1ODY1LCJleHAiOjE3NDAyNTIyNjV9.AweujjID0xXXnECYIhCU_WwzH60gvbBQiYCUjdMFjxg